export type IMapView = __esri.MapView | undefined;
export type IMap = __esri.Map | undefined;
export type IGraphic = __esri.Graphic | undefined;
export type ILayer= __esri.Layer | undefined;
export type ILayerView = __esri.LayerView | undefined;
export type IHandle = __esri.Handle | undefined;
export type IFeatureLayer = __esri.FeatureLayer | undefined;
export type IFeatureLayerView = __esri.FeatureLayerView | undefined;
export type ISearch = __esri.Search | undefined;
